//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Autor { get; set; }
        public Nullable<int> Genero { get; set; }
        public Nullable<int> Editorial { get; set; }
    
        public virtual Autor Autor1 { get; set; }
        public virtual Editorial Editorial1 { get; set; }
        public virtual Genero Genero1 { get; set; }


        public List<Autor> AutorList { get; set; }
        public List<Editorial> EditorialList { get; set; }
        public List<Genero> GeneroList { get; set; }





    }
}
